Update cleaner

diff --git a/system/xbin/cleaner b/system/xbin/cleaner
--- a/system/xbin/cleaner
+++ b/system/xbin/cleaner
@@ -1,24 +1,24 @@
 #!/system/bin/sh
 MODDIR=${0%/*}
 
-# Cache Cleaner (clear cache of all apps by typing 'su -c cleaner' in Terminal)
+# Cache Cleaner (clear cache of all apps by typing `su -c cleaner` in Terminal)
 clear
 
 echo "Cache+ (Magisk Module)"
+sleep 0.7
 echo "• A module that allows your device"
 echo "• To clear cache of all apps on every boot."
 echo ""
-sleep 1
+sleep 0.7
 echo "• And you can manually clear cache"
 echo "• By typing 'su -c cleaner' in Terminal."
 echo ""
-sleep 1
+sleep 0.7
 
-echo "! Error..."
-[ ! "$(whoami)" == "root" ] && echo "! Run as root user only." && exit 1
+[ ! "$(whoami)" == "root" ] && echo "! Error..." && echo "! Run as root user only." && exit 1
 
 echo "Do you want to clear cache of all apps? <yes/no>"
-printf "[CHOICE]: "
+printf "Your choice: "
 read clear
 if [ "$clear" == "yes" ]; then
     find /data/data/*/cache/* -delete &>/dev/null
